---
tools_library: !include tools.yml
common: # yaml shared by agent and all tools (can be overwritten by passing explicitly to constructors)
  llm: "facebook/bart-large-cnn"
  fast_llm: "facebook/bart-large-cnn"
  fast_llm_token_limit: 2500
  max_token_length: 4096
tools: # list of all tools available for the agent
  - load_inputs_tool
  - structure_financiere_comment_generation_tool
  - activite_et_rentabilite_comment_generation_tool
  - consolidation_tool
  - faits_marquants_comment_generation_tool
  - principaux_fournisseurs_comment_generation_tool
  - caracteristiques_secteur_activite_comment_generation_tool
  - principaux_clients_comment_generation_tool
  - description_moyens_exploitation_comment_generation_tool
  - actif_passif_comment_generation_tool
  - executive_summary_comment_generation_tool
  - garanties_mouvements_confies_comment_generation_tool
  - garanties_mouvements_international_comment_generation_tool
  - objet_demande_comment_generation_tool
  - etat_autorisations_utilisations_comment_generation_tool
action_plans: # list of all action plans available for the meta agent
  '1':
    name: ''
    description: Launch generation de la note
    actions:
      - - load_inputs_tool
      - - faits_marquants_comment_generation_tool
        - caracteristiques_secteur_activite_comment_generation_tool
        - principaux_fournisseurs_comment_generation_tool
        - principaux_clients_comment_generation_tool
        - description_moyens_exploitation_comment_generation_tool
        - activite_et_rentabilite_comment_generation_tool
        - structure_financiere_comment_generation_tool
        - actif_passif_comment_generation_tool
        - garanties_mouvements_confies_comment_generation_tool
        - garanties_mouvements_international_comment_generation_tool
        - objet_demande_comment_generation_tool
        - etat_autorisations_utilisations_comment_generation_tool
      - - executive_summary_comment_generation_tool
      - - consolidation_tool
prompt_message: |-
  Given the chat history and the user question, what action plan would be best to follow?
  Remember to only put out the number of the action plan you want to follow.

  User question: {input}
system_context: |-
  Your goal is to select the right action plan for the question of the user in the fastest way possible, given the chat history.

  Action plans:
  {action_plans}

  Only reply with the number of the action plan you want to follow and nothing else. For example: "1", "2", "3", etc.
